# Generated by Django 3.2.9 on 2021-11-10 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='this is a Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='this is a Package')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='this is a student'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='this is a Course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.lesson')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.package')),
                ('student', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
